Added Grafana questions and answers
bregman-arie/devops-exercises pull request #244
Opened 2022-05-20 10:07 UTC by AbyelT

Adding answers to questions in https://github.com/bregman-arie/devops-exercises/issues/4. Also added new questions and answers

2022-05-20 10:09 UTC, AbyelT commented
Hello @bregman-arie, i added some answers to existing questions from https://github.com/bregman-arie/devops-exercises/issues/4 and created some new questions about using and organizing an Grafana instance. I'm not fully done yet (some typo checking, references) but would love to hear feedback if you have any. Thanks in advance :)

2022-05-22 10:01 UTC, bregman-arie requested changes
Thanks for the effort. Left some comments.

2022-05-22 10:01 UTC, bregman-arie commented on exercises/grafana/README.md
> +<summary>How can we install plugins</summary><br><b>
How can we install plugins for Grafana?*

2022-05-22 10:01 UTC, bregman-arie commented on exercises/grafana/README.md
> +<summary>How is the version upgrade done</summary><br><b>
Same as "on which OS Grafana is supported?"

2022-05-29 20:39 UTC, AbyelT commented
Thanks for the feedback! I agree that some questions are redundant and the user can check the docs instead. I think the Q&A for Grafana is ready to merge, feel free to let me know if there is something to be addressed. Thanks in advance!

2022-05-30 08:40 UTC, bregman-arie approved these changes

2022-05-30 08:40 UTC, bregman-arie commented
Thanks for the effort

2022-05-30 08:40 UTC, merged