Added Testing Questions and Answers
bregman-arie/devops-exercises pull request #365
Opened 2023-03-26 07:26 UTC by chetanrakheja

2023-03-26 10:13 UTC, bregman-arie requested changes
Please give credit to the sites you copied the answers from

2023-03-26 13:55 UTC, chetanrakheja commented
Can you please confirm in which format credits need to be given and in which file

2023-05-27 17:42 UTC, bregman-arie commented
It can be as simple as mentioning the source name and link. There are many examples in the repository. Search for "wikipedia" for example.
As for the PDFs, if those written by your teacher, you can give him the credit, otherwise maybe remove those answers.

2023-05-28 18:26 UTC, andrzejsydor approved these changes

2024-02-02 13:17 UTC, closed without merging